add WEB_DEVPI_LOCKDOWN.
need to test it a bit before making a release version out of it.

diff --git a/nginx/bin/nginx-start b/nginx/bin/nginx-start
--- a/nginx/bin/nginx-start
+++ b/nginx/bin/nginx-start
@@ -8,15 +8,33 @@ set -eu
 mkdir -p /devpi/auth
 touch /devpi/auth/passwd
 
-envsubst '$WEB_SERVER_NAME,$WEB_DEVPI_SERVER,$WEB_PROXY_TIMEOUT,$WEB_CLIENT_MAX_BODY_SIZE' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
+envsubst '$WEB_SERVER_NAME,$WEB_DEVPI_SERVER,$WEB_PROXY_TIMEOUT,$WEB_CLIENT_MAX_BODY_SIZE' \
+         < "/etc/nginx/templates/nginx.conf" \
+         > "/etc/nginx/nginx.conf"
+
+if [ "${WEB_AUTH}" != "0" ] && [ "${WEB_DEVPI_LOCKDOWN}" != "0" ]; then
+  echo "WEB_AUTH and WEB_DEVPI_LOCKDOWN cannot be enabled at the same time"
+  exit 100
+fi
 
 if [ "${WEB_AUTH}" = "0" ]; then
+  truncate --size 0 /etc/nginx/include/auth.conf
+  truncate --size 0 /etc/nginx/include/proxy_remove_auth_header.conf
+else
+  truncate --size 0 /etc/nginx/include/lockdown.conf
+fi
+
+if [ "${WEB_DEVPI_LOCKDOWN}" = "0" ]; then
+  truncate --size 0 /etc/nginx/include/lockdown.conf
+else
   truncate --size 0 /etc/nginx/include/auth.conf
 fi
 
 if [ "${DEBUG}" != "0" ]; then
   cat /etc/nginx/nginx.conf
-  cat /etc/nginx/include/auth.conf
+  for f in /etc/nginx/include/*.conf; do
+    cat ${f}
+    done
 fi
 
 exec nginx "$@"
